name: GitHub Upload 
on: [push]
jobs:
  upload_files:
    runs-on: ubuntu-latest
    name: Upload a builded file.
    steps:
    - run: echo "🎉 😀🤭😘🤣 ip  ${{ secrets.IP }} username ${{ secrets.USER_NAME }} :) ."

    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Upload Files
      id: upload
      uses: Creepios/sftp-action@v1.0.3
      with:
      # secret from repository secrets!!!
        host: ' ${{ secrets.IP }}'
        port: 22
        username: '${{ secrets.USER_NAME }}'
        password: '${{ secrets.PASSWORD }}'
        localPath: '.'
        remotePath: './applications/wyvdevvkhg/public_html'
